I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script12.rpy", line 154, in script
    scene credits with dissolve(5.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script12.rpy", line 154, in script
    scene credits with dissolve(5.0)
  File "renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2762, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3676, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
Botanic Mystery 
Sun Mar 27 18:56:47 2022
